// Code generated by protoc-gen-go.
// source: sum.proto
// DO NOT EDIT!

/*
Package grpc_template is a generated protocol buffer package.

It is generated from these files:
	sum.proto
	sum_rpc.proto

It has these top-level messages:
	RpcTemplateRequest
	RpcTemplateResponse
*/
package grpc_template

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type RpcTemplateRequest struct {
	Items []int32 `protobuf:"varint,1,rep,name=items" json:"items,omitempty"`
}

func (m *RpcTemplateRequest) Reset()                    { *m = RpcTemplateRequest{} }
func (m *RpcTemplateRequest) String() string            { return proto.CompactTextString(m) }
func (*RpcTemplateRequest) ProtoMessage()               {}
func (*RpcTemplateRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type RpcTemplateResponse struct {
	Result int32 `protobuf:"varint,1,opt,name=result" json:"result,omitempty"`
}

func (m *RpcTemplateResponse) Reset()                    { *m = RpcTemplateResponse{} }
func (m *RpcTemplateResponse) String() string            { return proto.CompactTextString(m) }
func (*RpcTemplateResponse) ProtoMessage()               {}
func (*RpcTemplateResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func init() {
	proto.RegisterType((*RpcTemplateRequest)(nil), "grpc_template.RpcTemplateRequest")
	proto.RegisterType((*RpcTemplateResponse)(nil), "grpc_template.RpcTemplateResponse")
}

func init() { proto.RegisterFile("sum.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 118 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x2c, 0x2e, 0xcd, 0xd5,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0xe2, 0x4d, 0x2f, 0x2a, 0x48, 0x8e, 0x2f, 0x49, 0xcd, 0x2d,
	0xc8, 0x49, 0x2c, 0x49, 0x55, 0xd2, 0xe2, 0x12, 0x0a, 0x2a, 0x48, 0x0e, 0x81, 0x72, 0x83, 0x52,
	0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x44, 0xb8, 0x58, 0x33, 0x81, 0x4a, 0x8a, 0x25, 0x18, 0x15,
	0x98, 0x35, 0x58, 0x83, 0x20, 0x1c, 0x25, 0x5d, 0x2e, 0x61, 0x14, 0xb5, 0xc5, 0x05, 0xf9, 0x79,
	0xc5, 0xa9, 0x42, 0x62, 0x5c, 0x6c, 0x45, 0xa9, 0xc5, 0xa5, 0x39, 0x25, 0x40, 0xd5, 0x8c, 0x40,
	0xd5, 0x50, 0x5e, 0x12, 0x1b, 0xd8, 0x42, 0x63, 0x40, 0x00, 0x00, 0x00, 0xff, 0xff, 0x79, 0x9e,
	0x88, 0xcc, 0x7d, 0x00, 0x00, 0x00,
}
